- name: Event log policy test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "Set event log policy"
    edit_event_log_policy:
      policy: "Linear"
      provider: "{{ ism }}"