- name: Power consumption test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "Get power consumption information"
    power_consumption_info:
      provider: "{{ ism }}"