- name: clear BMC audit log  test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "clear BMC audit log "
    clear_audit_log:
      provider: "{{ ism }}"