- name: boot test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "set bios boot option"
    edit_boot_option:
      device: "PXE"
      effective: "Once"
      mode: "Legacy"
      provider: "{{ ism }}"