- name: bios test
  hosts: ism
  collections:
    - inspur.sm
  connection: local
  gather_facts: no
  vars:
    ism:
      host: "{{ ansible_ssh_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

  - name: "set bios setup"
    edit_bios:
      attribute: "VMX"
      value: "Disable"
      provider: "{{ ism }}"

  - name: "set bios setup"
    edit_bios:
      attribute: "VMX"
      value: "Enable"
      provider: "{{ ism }}"